[Plang-2151] Pipeline intermediate files
bitrise-steplib/steps-deploy-to-bitrise-io pull request #158
Opened 2022-07-29 09:53 UTC by tothszabi

### Checklist

- [ ] I've read and followed the [Contribution Guidelines](https://github.com/bitrise-steplib/.github/blob/main/CONTRIBUTING.md)
- [ ] `step.yml` and `README.md` is updated with the changes (if needed)

### Version

Requires a *MINOR* [version update](https://semver.org/)

### Context

The main goal of this PR is introduce better pipeline intermediate file sharing handling. The step uses the new `intermediate_file_info` metadata field to store the environment variable name and file type. This way the artifact-pull step can restore the environment variable and its value automatically.

### Changes

- The step.yml file was rearranged. The step now has two main aspect: regular deploy and intermediate file sharing. The inputs are grouped to have better visibility on what belongs together.
  - There is a new `pipeline_intermediate_files` input value
- There are dedicated deploy functions for the known files (ipa, xcarchive, apk, aab) which do almost the same thing but refactoring them was not in scope for now. They all have gained the ability to attach the pipeline metadata info to the upload action.
- The step was mainly passing paths between its functions which was changed to be a `deployment.DeployableItem` struct which holds the extra pipeline metadata info associated with the given path
- The main logic is in the `deployment.Collector` struct
  - It parses the intermediate file list
  - Combines the intermediate file list with the regular deployable items
    - A deployable item also can be an intermediate file and in this case we do not want to upload the file twice
  - Zips the intermediate files which were actually fodlers

2022-08-03 07:13 UTC, godrei approved these changes

2022-08-03 07:16 UTC, daniCsorba requested changes
I reviewed and left some technical writing comments for the step.yml file.

2022-08-03 07:16 UTC, daniCsorba commented on step.yml
>          The `path` is the path to the file or folder and the `env_key` is the name of the environment variable to which this value is associated.
I'd recommend changing this to:
The `path` is the path to the file or folder. The `env_key` is the name of the environment variable with which this value is associated.

2022-08-03 08:53 UTC, godrei submitted a review, later dismissed

2022-08-03 13:48 UTC, godrei commented on docs/examples.md
> +The Step supports sharing files between pipeline stages. The input needs to be a newline separated **value:env_key_name** list. This metadata will be saved with the individual files and restored by t
Artifact pull Step -> Pull Pipeline intermediate files Step

2022-08-03 14:03 UTC, godrei submitted a review, later dismissed

2022-08-05 13:15 UTC, godrei approved these changes

2022-08-05 13:18 UTC, merged